version: '3.8'

services:
  backend:
    build:
      context: ./adicorp_server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./adicorp_server:/app

  frontend:
    build:
      context: ./adicorp_app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./adicorp_app:/app
    stdin_open: true
    tty: true

