version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./adicorp_server:/app
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./adicorp_app:/app
    stdin_open: true
    tty: true

